Repository windup/windup-rulesets, pull requests merged in 2020-01, with the labels that each got.

#376 WINDUPRULE-392 Maven dependecies
  rules-reviewed/camel3/camel2/tests/data/xml-java-versions/pom.xml
  rules-reviewed/camel3/camel2/tests/xml-java-versions.windup.test.xml
  rules-reviewed/camel3/camel2/xml-java-versions.windup.xml
Labels: Work in Progress/For Discussion Only

#377 WINDUPRULE-393 'context' attribute removed
  rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml
  rules-reviewed/camel3/camel2/tests/data/java-multiple-camelcontexts-per-application-not-supported/Removed.java
  rules-reviewed/camel3/camel2/tests/java-multiple-camelcontexts-per-application-not-supported.windup.test.xml
Labels: Work in Progress/For Discussion Only

#394 WINDUPRULE-427 WindupRulesLinksTest and fixed links
  pom.xml
  rules-reviewed/eap6/java-ee/seam/seam-java.windup.xml
  rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
  rules-reviewed/eap6/websphere/websphere-xml.windup.xml
  rules-reviewed/eap7/eap5and6/jboss-eap5and6to7-xml.windup.xml
  rules-reviewed/eap7/eap6/hibernate4.windup.xml
  rules-reviewed/eap7/eap6/hsearch.windup.xml
  rules-reviewed/eap7/eap6/resteasy.windup.xml
  rules-reviewed/eap7/eap70/hibernate50-51.windup.xml
  rules-reviewed/eap7/websphere/websphere-xml.windup.xml
  rules-reviewed/openshift/local-storage.windup.xml
  rules-reviewed/openshift/mail.windup.xml
  src/test/java/org/jboss/windup/rules/tests/WindupRuleValidationTestSuite.java
  src/test/java/org/jboss/windup/rules/tests/WindupRulesLinksTest.java
Labels: Ready to Review

#402 WINDUPRULE-439 Fixed broken links using latest IBM docs
  rules-reviewed/eap6/websphere/websphere-xml.windup.xml
  rules-reviewed/eap7/websphere/websphere-xml.windup.xml
Labels: Ready to Review

#392 WINDUPRULE-403 SessionBean interface removed
  rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.groovy
  rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.xml
  rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/AnotherCounter.java
  rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/Counter.java
  rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/SingletonBean.java
  rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/SingletonNoSessionBeanBean.java
  rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/ejb-jar.xml
  rules-reviewed/eap7/eap72/tests/singleton-sessionbean.rhamt.test.xml
Labels: Depends on another PR/Release, Ready to Review

#397 WINDUPRULE-411 Camel 3 springboot starters groupId have been renamed
  rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
  rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
  rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml
Labels: Depends on another PR/Release

#381 WINDUPRULE-396: eap 7.3 maven-javax-to-jakarta rules
  rules-reviewed/eap7/eap72/maven-javax-to-jakarta.rhamt.xml
  rules-reviewed/eap7/eap72/tests/data/data-maven-javax-to-jakarta/pom.xml
  rules-reviewed/eap7/eap72/tests/maven-javax-to-jakarta.rhamt.test.xml
Labels: Ready to Review
