Repository windup/windup-rulesets, pull requests merged in 2023-02, with the labels that each got.

#848 Fixing URLs
  rules/rules-reviewed/azure/springboot/spring-boot-to-azure-cache.windup.xml
  rules/rules-reviewed/azure/springboot/spring-boot-to-azure-feign.windup.xml
  rules/rules-reviewed/quarkus/springboot/springboot-shell-to-quarkus.windup.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#855 WINDUPRULE-934 Added CDI Jakarta technology-tag
  rules/rules-reviewed/technology-usage/embedded-framework-technology-usage.windup.xml
  rules/rules-reviewed/technology-usage/javaee-technology-usage.windup.xml
  rules/rules-reviewed/technology-usage/tests/data/javaee/JsonControllerJakarta.java
  rules/rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/javaee-technology-usage.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#853 [WINDUPRULE-899] Ruleset for hibernate orm 6.0 migration
  rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate6/Employee.hbm.xml
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate6/HibernateOrm6TestClass.java
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate6/hibernate6.properties
  rules/rules-reviewed/eap8/eap7/tests/hibernate6.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#856 [WINDUPRULE-895] Jakarta restful webservices
  rules/rules-reviewed/eap8/eap7/jakarta-ws-rs.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/ws-rs/WsRs.java
  rules/rules-reviewed/eap8/eap7/tests/jakarta-ws-rs.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#860 [WINDUPRULE-906] Rules for javax/jakarta EL
  rules/rules-reviewed/eap8/eap7/jakarta-el.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/jakarta-el/JakartaEL.java
  rules/rules-reviewed/eap8/eap7/tests/jakarta-el.windup.test.xml
  rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#862 [WINDUPRULE-910] Rule for jakarta json binding
  rules/rules-reviewed/eap8/eap7/jakarta-json-binding.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/jakarta-json-binding/JakartaJsonBinding.java
  rules/rules-reviewed/eap8/eap7/tests/jakarta-json-binding.windup.test.xml
Labels: Ready to Review

#859 [WINDUPRULE-902] Add picketlink ruleset
  rules/rules-reviewed/eap8/eap7/picketlink.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/picketlink/WEB-INF/picketlink-sts.xml
  rules/rules-reviewed/eap8/eap7/tests/data/picketlink/WEB-INF/picketlink.xml
  rules/rules-reviewed/eap8/eap7/tests/picketlink.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#858 [WINDUPRULE-901] Add ruleset for legacy vault removal
  rules/rules-reviewed/eap8/eap7/legacy-vault.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/legacy-vault/LegacyVault.java
  rules/rules-reviewed/eap8/eap7/tests/data/legacy-vault/jboss-app.xml
  rules/rules-reviewed/eap8/eap7/tests/legacy-vault.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#866 WINDUPRULE-897: Rules to move to Jakarta XML Binding 4.0
  rules/rules-reviewed/eap8/eap6/eap8-xml-binding.windup.xml
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/META-INF/services/javax.xml.bind.JAXBContext
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/SunApiPackageTest.java
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/SunV2PackageTest.java
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/jaxb.properties
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/pom.xml
  rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/test.xjb
  rules/rules-reviewed/eap8/eap6/tests/eap8-xml-binding.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#874 WINDUP-3692 'hibernate6' rules refactoring
  rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
Labels: auto-backport, auto-backport-to-releases/6.1.z

#881 Restrict IO classes to only Files
  rules/rules-reviewed/azure/azure-file-system.windup.xml
  rules/rules-reviewed/azure/tests/azure-file-system.windup.test.xml
  rules/rules-reviewed/azure/tests/data/azure-file-system/FileSystem.java
Labels: Ready to Review
