Repository windup/windup-rulesets, pull requests merged in 2023-03, with the labels that each got.

#888 [WINDUPRULE-966] Add @GeneratedValue rule
  rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate6/HibernateOrm6TestClass.java
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate6/hibernate-core-5.5.5.Final.jar
  rules/rules-reviewed/eap8/eap7/tests/hibernate6.windup.test.xml
  rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml
Labels: auto-backport, auto-backport-to-releases/6.1.z

#887 [WINDUPRULE-963] Improve hibernate-search-6.1-00010
  rules/rules-reviewed/eap8/eap7/hibernate-search-6.1.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/data/hibernate-search-61/pom.xml
  rules/rules-reviewed/eap8/eap7/tests/hibernate-search-6.1.windup.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#897 WINDUPRULE-969 'hibernate6' migration target alias
  rules/rules-reviewed/eap8/hibernate6.windup.technologytransformer.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#901 WINDUPRULE-966 Removed 'hibernate' dependency conditions
  rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#908 [WINDUPRULE-920] Fix typo
  rules/rules-reviewed/eap8/eap7/jakarta-faces.windup.xml
  rules/rules-reviewed/eap8/eap7/tests/jakarta-faces.windup.test.xml
Labels: Ready to Review

#912 [WINDUPRULE-956] Narrow down properties rules to look only in some files
  rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
Labels: Ready to Review

#913 Fixed 'spring-boot-to-azure-eureka-01000' rule's link
  rules/rules-reviewed/azure/springboot/spring-boot-to-azure-eureka.windup.xml
  rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z
