Repository windup/windup-rulesets, pull requests merged in 2023-05, with the labels that each got.

#934 WINDUPRULE-983 Update versions of SpringBoot supported by RHR
  rules/rules-reviewed/rhr/springboot/springboot-rhr.rhamt.xml
  rules/rules-reviewed/rhr/springboot/tests/.windup/cache/nexus-indexer-data/test.archive-metadata.txt
  rules/rules-reviewed/rhr/springboot/tests/data/spring-boot-starter-web-3.0.0.jar
  rules/rules-reviewed/rhr/springboot/tests/springboot-rhr.rhamt.test.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#941 Enhanced tests to support '/*' syntax for 'testDataPath' tag
  rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesMultipleTests.java
  rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java
Labels: Ready to Review

#944 WindupRulesLinksTest job needs windup-build job
  .github/workflows/pr_build_jdk11.yml
Labels: auto-backport, auto-backport-to-releases/6.2.z

#947 WINDUPRULE-985 Fixed 'number-found' consistently with actual values in the reports
  rules/rules-reviewed/technology-usage/tests/configuration-management-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/database-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/integration-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/jta-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/logging-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/markup-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/mvc-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/non-xml-rules-technology-usage.rhamt.test.xml
  rules/rules-reviewed/technology-usage/tests/security-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/web-technology-usage.windup.test.xml
Labels: Ready to Review

#962 WINDUPRULE-996/WINDUPRULE-993 'Kafka Client' technology rules and 'connect' techology rules to Groovy
  rules/rules-reviewed/technology-usage/connect-technology-usage.windup.xml
  rules/rules-reviewed/technology-usage/connect.windup.groovy
  rules/rules-reviewed/technology-usage/connect.windup.xml
  rules/rules-reviewed/technology-usage/tests/connect-spring-messaging.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/connect-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/connect.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/data/connect/kafka-clients
  rules/rules-reviewed/technology-usage/tests/data/connect/spring-kafka
  rules/rules-reviewed/technology-usage/tests/javaee-technology-tag.windup.test.xml
Labels: Ready to Review

#924 Add new runtime springboot and add JPA as supported
  rules-themed/rules-windup/labels/core.windup.label.xml
  rules-themed/rules-windup/labels/embedded.windup.label.xml
  rules/rules-reviewed/README.md
  rules/rules-reviewed/technology-usage/3rd-party-spring-technology-usage.windup.xml
  rules/rules-reviewed/technology-usage/3rd-party-spring.windup.xml
  rules/rules-reviewed/technology-usage/tests/3rd-party-spring-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/3rd-party-spring.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/data/3rd-party-spring/SimpleWebApplication.java
  rules/rules-reviewed/technology-usage/tests/data/3rd-party-spring/WebInitializer.java
  rules/rules-reviewed/technology-usage/tests/data/3rd-party-spring/web.xml
Labels: Ready to Review

#974 WINDUP-3889 Refectoted cloud-readiness rulesets
  rules/rules-reviewed/cloud-readiness/embedded-cache-libraries.windup.xml
  rules/rules-reviewed/cloud-readiness/java-rmi.windup.xml
  rules/rules-reviewed/cloud-readiness/java-rpc.windup.xml
  rules/rules-reviewed/cloud-readiness/jca.windup.xml
  rules/rules-reviewed/cloud-readiness/jni-native-code.windup.xml
  rules/rules-reviewed/cloud-readiness/local-storage.windup.xml
  rules/rules-reviewed/cloud-readiness/logging.windup.xml
  rules/rules-reviewed/cloud-readiness/mail.windup.xml
  rules/rules-reviewed/cloud-readiness/session.windup.xml
  rules/rules-reviewed/cloud-readiness/socket-communication.windup.xml
  rules/rules-reviewed/cloud-readiness/tests/data/Hello.java
  rules/rules-reviewed/cloud-readiness/tests/data/HelloImpl.java
  rules/rules-reviewed/cloud-readiness/tests/data/JNI.java
  rules/rules-reviewed/cloud-readiness/tests/data/LocalFileUsage.java
  rules/rules-reviewed/cloud-readiness/tests/data/Logging.java
  rules/rules-reviewed/cloud-readiness/tests/data/Mail.java
  rules/rules-reviewed/cloud-readiness/tests/data/RPC.java
  rules/rules-reviewed/cloud-readiness/tests/data/Session.java
  rules/rules-reviewed/cloud-readiness/tests/data/SocketCommunication.java
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/cache-api-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/coherence-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/commons-jcs-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/demo-0.0.1-SNAPSHOT.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/dynacache-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/ehcache-1.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/hazelcast-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/ignite-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/infinispan-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/jbosscache-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/jcache-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/memcached-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/oscache-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/pom.xml
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/shiftone-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/embedded-cache-libraries/swarmcache-1.2.3.1.jar
  rules/rules-reviewed/cloud-readiness/tests/data/example.jpg
  rules/rules-reviewed/cloud-readiness/tests/data/example.png
  rules/rules-reviewed/cloud-readiness/tests/data/java.properties
  rules/rules-reviewed/cloud-readiness/tests/data/log4j.properties
  rules/rules-reviewed/cloud-readiness/tests/data/log4j.xml
  rules/rules-reviewed/cloud-readiness/tests/data/ra.xml
  rules/rules-reviewed/cloud-readiness/tests/data/web.xml
  rules/rules-reviewed/cloud-readiness/tests/embedded-cache-libraries.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/java-rmi.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/java-rpc.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/jca.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/jni-native-code.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/local-storage.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/logging.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/mail.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/session.windup.test.xml
  rules/rules-reviewed/cloud-readiness/tests/socket-communication.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
  rules/rules-reviewed/technology-usage/tests/logging-technology-usage.windup.test.xml
Labels: Ready to Review
